### PR TITLE
Controller2

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Add message converters
  - Add message converters that registers the converters for the given types

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
These changes let the XD shell talk to s-c-data admin provided the SpringXDTemplate's links are commented out except for streams.

**Comment by markfisher** [comment]
do we still have the same situation with multiple possible versions of jackson and the need to check jaxb2 as well?

**Comment by markfisher** [comment]
If we keep this code overall, it should move to a static method within the Configuration class itself. Something that is only used in one place should not be in a *Util class IMO.

**Comment by pperalta** [comment]
Closed in favor of https://github.com/spring-cloud/spring-cloud-data/pull/17/

**Pull request closed without merging**
